# Generated by Django 4.0.2 on 2022-03-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_appointment_speciality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_end_time',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_start_time',
            field=models.CharField(max_length=500),
        ),
    ]
